name: CI E2E Tests NTK on Push TAG
on:
  workflow_call:

defaults:
  run:
    working-directory: /home/runner/work/

jobs:
   build-tests:
    name: Run Playwright Tests
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    outputs:
      REP_NAME: ${{ steps.prep.outputs.REP_NAME }}
      SHORT_SHA: ${{ steps.prep.outputs.SHORT_SHA }} 
      SHORT_REF_NAME: ${{ steps.prep.outputs.SHORT_REF_NAME }}
      RELEASE: ${{ steps.prep.outputs.RELEASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Prepare Vars
        id: prep
        run: |
          echo "REP_NAME=`echo ${GITHUB_REPOSITORY} | cut -d "/" -f2 `" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
          echo "RELEASE=`echo $(date +'%Y_R%q')`" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
          if [[ ${{ github.ref_type }} == 'branch' ]]; then
            echo "SHORT_REF_NAME=`echo ${{ github.ref_name }}`" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
          else
            echo "SHORT_REF_NAME=`echo ${{ github.event.base_ref }} | cut -d "/" -f3`" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
          fi


      - name: Delete Tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          #delete_release: false # default: false
          tag_name: ${{ github.ref_name }} # tag name to delete
          #repo: ${{ github.repository_owner }}/${{ env.REP_NAME }} # target repo (optional). defaults to repo running this action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 💿 Setup NODEJS
        uses: actions/setup-node@v4
        id: node_inst
        with:
          node-version: 20

      - name: ▶️ Install Node.js dependencies
        run: ls -la ./ && npm ci
        working-directory: ./

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./
        env:
          PLAYWRIGHT_BROWSERS_PATH: ./browsers


      - name: Run Once
        # run: cd ./novatalks.tests/novatalks.tests/ && npx playwright test QANT-16-TimerStatus.spec.ts
        # run: npx playwright test QANT-16-TimerStatus.spec.ts
        run: npx playwright test--grep @bug
        working-directory: ./
        env:
          ENV_URL: ${{ secrets.LAB_ENV_URL }}
          BOTFLOW_ADMIN_LOGIN: ${{ secrets.LAB_BOTFLOW_ADMIN_LOGIN }}
          BOTFLOW_ADMIN_PASSWORD: ${{ secrets.LAB_BOTFLOW_ADMIN_PASSWORD }}
          UI_ADMIN_LOGIN: ${{ secrets.LAB_UI_ADMIN_LOGIN }}
          UI_ADMIN_PASSWORD: ${{ secrets.LAB_UI_ADMIN_PASSWORD }}
          API_TOKEN: ${{ secrets.LAB_API_TOKEN }}
          PLAYWRIGHT_BROWSERS_PATH: ./browsers


      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30



