name: CI Build Trigger Switcher
on:
  workflow_call:
    inputs:
      runner_label:
        required: true
        type: string
      server_id:
        required: true
        type: string
    

jobs:
  preparation:
    name: CI Build Trigger Switcher Start
    runs-on: ${{ inputs.runner_label }}
    steps:
      - name: Catch Github Events
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_CONTEXT
          echo ${{ github.event_name == 'push' }}
          echo ${{ contains(github.ref, 'tags') }}
          echo ${{ contains(github.ref, 'build') }}
  

  call-external-on-push-tags:
    name: Call Builder On Push Tags
    if: ${{ contains(fromJSON('["novatalks.engine", "nova.core", "novatalks.ui", "nova.botflow", "nova.chatsconnector.telegram-client-api", "novatalks.dialer", "nova.chatsconnector.genesys.cloud.premium.wizard.engine" ]'), github.event.repository.name) && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && contains(github.ref_name, 'build') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-build.yaml@main
    secrets: inherit
    with:
      runner_label: ${{ inputs.runner_label }}
      server_id: ${{ inputs.server_id }}

  call-external-on-pull-request-merged:
    name: Call Builder On Merge PR
    if: ${{ contains(fromJSON('["novatalks.engine", "novatalks.ui", "nova.core", "nova.botflow", "nova.chatsconnector.telegram-client-api", "novatalks.dialer", "nova.chatsconnector.genesys.cloud.premium.wizard.engine" ]'), github.event.repository.name) && github.event_name == 'push' && github.ref_type == 'branch' && contains(github.event.head_commit.message, 'build') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-build.yaml@main
    secrets: inherit
    with:
      runner_label: ${{ inputs.runner_label }}
      server_id: ${{ inputs.server_id }}

  call-external-on-push-tags-run-test:
    name: Call Test Runner On Push Tags
    if: ${{ github.event.repository.name == 'novatalks.engine' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'int-test') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-run-test.yaml@main
    secrets: inherit


  call-external-on-push-tags-gh-deploy:
    name: Call GH Pages Deploy On Push Tags
    if: ${{ github.event.repository.name == 'nova.docs' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'build') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-gh-deploy.yaml@main
    secrets: inherit

  call-external-on-push-tags-mob-apk-build:
    name: Call Mobile APK Build On Push Tags
    if: ${{ github.event.repository.name == 'novatalks.ui-lite' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'build-apk') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-mob-apk-build.yaml@main
    secrets: inherit

  call-external-on-push-tags-mob-apk-build-public:
    name: Call Mobile APK Build On Push Tags
    if: ${{ github.event.repository.name == 'novatalks.mobile' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'build-apk') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-mob-apk-build-public.yaml@main
    secrets: inherit    

    
  call-external-on-push-tags-mob-pwa-build:
    name: Call Mobile PWA Build On Push Tags
    if: ${{ github.event.repository.name == 'novatalks.ui-lite' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'build-pwa') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-mob-pwa-build.yaml@main
    secrets: inherit

  call-external-on-push-tags-mob-spa-build:
    name: Call Mobile SPA Build On Push Tags
    if: ${{ github.event.repository.name == 'novatalks.ui-lite' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'build-spa') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-mob-pwa-build.yaml@main
    secrets: inherit
  
  call-external-on-push-tags-crm-build:
    name: Call Mobile SPA Build On Push Tags
    if: ${{ github.event.repository.name == 'novatalks.ui-lite' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'build-crm') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-mob-pwa-build.yaml@main
    secrets: inherit

  call-external-on-push-tags-widget-build:
    name: Call GH Pages Deploy On Push Tags
    if: ${{ github.event.repository.name == 'novatalks.chatwidget' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'build') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-widget-build.yaml@main
    secrets: inherit


  call-external-on-push-branches:
    name: Call Builder If Push Certain Branches
    if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && contains(github.ref_name, 'build-me-please') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-branches.yaml@main
    secrets: inherit

  call-external-on-push-branches-e2e-tests:
    name: Call Playwright Tests
    if: ${{ github.event.repository.name == 'novatalks.tests' && github.event_name == 'push' && github.ref_type == 'tag' && contains(github.ref_name, 'playtest') }}
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-ntk-on-push-tags-run-e2e.yaml@main
    secrets: inherit

  delete-runner:
    name: Delete Hetzner Cloud runner
    runs-on: ubuntu-latest
    if: ${{ needs.call-external-on-push-tags.result != 'success' &&
          needs.call-external-on-pull-request-merged.result != 'success' &&
          needs.call-external-on-push-tags-run-test.result != 'success' &&
          needs.call-external-on-push-tags-gh-deploy.result != 'success' &&
          needs.call-external-on-push-tags-mob-apk-build.result != 'success' &&
          needs.call-external-on-push-tags-mob-apk-build-public.result != 'success' &&
          needs.call-external-on-push-tags-mob-pwa-build.result != 'success' &&
          needs.call-external-on-push-tags-mob-spa-build.result != 'success' &&
          needs.call-external-on-push-tags-crm-build.result != 'success' &&
          needs.call-external-on-push-tags-widget-build.result != 'success' &&
          needs.call-external-on-push-branches.result != 'success' &&
          needs.call-external-on-push-branches-e2e-tests.result != 'success' }}
    needs:
      - preparation
      - call-external-on-push-tags
      - call-external-on-pull-request-merged
      - call-external-on-push-tags-run-test
      - call-external-on-push-tags-gh-deploy
      - call-external-on-push-tags-mob-apk-build
      - call-external-on-push-tags-mob-apk-build-public
      - call-external-on-push-tags-mob-pwa-build
      - call-external-on-push-tags-mob-spa-build
      - call-external-on-push-tags-crm-build
      - call-external-on-push-tags-widget-build
      - call-external-on-push-branches
      - call-external-on-push-branches-e2e-tests
    steps:
      - name: Delete runner
        uses: volodymyrmanzhula-nova/hcloud-github-runner@master
        with:
          mode: delete
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          name: ${{ inputs.runner_label }}
          server_id: ${{ inputs.server_id }}


