name: CI Build NTK on Push TAG
on:
  workflow_call:


jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: mkdir -p ./mkdocs-material/material

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Isntall Dependency and Build
        run: |
         pip install mkdocs
         pip install mkdocs-material
         pip install mkdocs-material-extensions
         pip install mkdocs-include-markdown-plugin
         pip install mkdocs-redirects
         mkdocs build

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ./mkdocs.yml
          REQUIREMENTS: ./req.txt